# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fce2bda5316ca4b6fabea5185c2aa3156fa365eb81a2ba03222e4023d799220199bdd5b8bc3d7f928a3b8f10e51c9564df660ee79f7b63f2cfc09099518e66b

test:
  secret_key_base: a52f20e22065faa3c2dcee04b181a242cc28b900b88420bd8e4548800a39d7be87a9600a55ae9df5bce9e81b0ccfc677867c4b79015516daa8f1ca7cbcdac762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
